In [1]:
# Series
#attr: .index, .values, .name, .index.name, .values.name

In [7]:
import pandas as pd
import numpy as np

In [3]:
data = {'state':['ohio','ohio','ohio','nev','nev'], 'year':[2000,2001,2002,2003,2004],
       'pop':[1.5,1.3,1.7,2.0,3.5]}
pd.Series(data)

pop           [1.5, 1.3, 1.7, 2.0, 3.5]
state      [ohio, ohio, ohio, nev, nev]
year     [2000, 2001, 2002, 2003, 2004]
dtype: object

In [4]:
#DataFrame
#attr: .columns, .index, .values

In [5]:
pd.DataFrame(data)

pop state  year
0  1.5  ohio  2000
1  1.3  ohio  2001
2  1.7  ohio  2002
3  2.0   nev  2003
4  3.5   nev  2004

In [9]:
#二维ndarray，可以传入行标和列标
ARR = np.array([[1,2,3,4],[5,6,7,8]])
print(ARR)

[[1 2 3 4]
 [5 6 7 8]]


In [11]:
ff = pd.DataFrame(ARR, columns = list('abcd'), index=['first','second'])
print(ff)

        a  b  c  d
first   1  2  3  4
second  5  6  7  8


In [14]:
#指定列，DataFrame的列会按照指定的顺序进行排列，和Series指定索引一样
pd.DataFrame(data,columns = ['pop','year','state'])

pop  year state
0  1.5  2000  ohio
1  1.3  2001  ohio
2  1.7  2002  ohio
3  2.0  2003   nev
4  3.5  2004   nev

In [15]:
pd.Series(data, index=['pop','year','state'])

pop           [1.5, 1.3, 1.7, 2.0, 3.5]
year     [2000, 2001, 2002, 2003, 2004]
state      [ohio, ohio, ohio, nev, nev]
dtype: object

In [16]:
#如果传入的列在数据中找不到就会产生NA，和Series一样
pd.DataFrame(data,columns = ['pop','year','state',"add"])

pop  year state  add
0  1.5  2000  ohio  NaN
1  1.3  2001  ohio  NaN
2  1.7  2002  ohio  NaN
3  2.0  2003   nev  NaN
4  3.5  2004   nev  NaN

In [17]:
pd.Series(data, index = ['pop','year','state',"add"])

pop           [1.5, 1.3, 1.7, 2.0, 3.5]
year     [2000, 2001, 2002, 2003, 2004]
state      [ohio, ohio, ohio, nev, nev]
add                                 NaN
dtype: object

In [18]:
#更改行索引
pd.DataFrame(data, index = list('abcde'))

pop state  year
a  1.5  ohio  2000
b  1.3  ohio  2001
c  1.7  ohio  2002
d  2.0   nev  2003
e  3.5   nev  2004

In [19]:
f = pd.DataFrame(data, index = list('abcde'))

In [20]:
f.index

Index(['a', 'b', 'c', 'd', 'e'], dtype='object')

In [21]:
f.columns

Index(['pop', 'state', 'year'], dtype='object')

In [22]:
f.values # 以二维ndarray的形式返回数据

array([[1.5, 'ohio', 2000],
       [1.3, 'ohio', 2001],
       [1.7, 'ohio', 2002],
       [2.0, 'nev', 2003],
       [3.5, 'nev', 2004]], dtype=object)

In [23]:
s = pd.Series(data, index = ['pop','year','state',"add"])

In [24]:
s.index

Index(['pop', 'year', 'state', 'add'], dtype='object')

In [25]:
s.values

array([[1.5, 1.3, 1.7, 2.0, 3.5], [2000, 2001, 2002, 2003, 2004],
       ['ohio', 'ohio', 'ohio', 'nev', 'nev'], nan], dtype=object)

In [27]:
#指定列
f['pop']

a    1.5
b    1.3
c    1.7
d    2.0
e    3.5
Name: pop, dtype: float64

In [28]:
#利用属性获取
f.year

a    2000
b    2001
c    2002
d    2003
e    2004
Name: year, dtype: int64

In [29]:
s.year

[2000, 2001, 2002, 2003, 2004]

In [30]:
s['year']

[2000, 2001, 2002, 2003, 2004]

In [31]:
s[1]

[2000, 2001, 2002, 2003, 2004]

In [38]:
#获取行：行可以通过位置或名称的方式进行索引
f.ix['a']

pop       1.5
state    ohio
year     2000
Name: a, dtype: object

In [40]:
#添加行
f['add'] = [10,20,30,40,50]
f

pop state  year  add
a  1.5  ohio  2000   10
b  1.3  ohio  2001   20
c  1.7  ohio  2002   30
d  2.0   nev  2003   40
e  3.5   nev  2004   50

In [41]:
s['add'] = (1,2,3,4,5)

In [42]:
#删除列
del f['add']

In [43]:
#转置
f.T

a     b     c     d     e
pop     1.5   1.3   1.7     2   3.5
state  ohio  ohio  ohio   nev   nev
year   2000  2001  2002  2003  2004

In [44]:
#reindex
f.reindex(list('bcadef'))

pop state    year
b  1.3  ohio  2001.0
c  1.7  ohio  2002.0
a  1.5  ohio  2000.0
d  2.0   nev  2003.0
e  3.5   nev  2004.0
f  NaN   NaN     NaN

In [45]:
#缺失值用0填充
f.reindex(list('bcadef'), fill_value = 0)

pop state  year
b  1.3  ohio  2001
c  1.7  ohio  2002
a  1.5  ohio  2000
d  2.0   nev  2003
e  3.5   nev  2004
f  0.0     0     0

In [47]:
#method选项对确实只进行插值处理，ffill/pad：前向填充； bfill/backfill：后向填充
f.reindex(list('bcadef'),method = "ffill")

pop state  year
b  1.3  ohio  2001
c  1.7  ohio  2002
a  1.5  ohio  2000
d  2.0   nev  2003
e  3.5   nev  2004
f  3.5   nev  2004

In [48]:
# DataFrame数据格式不仅可以修改行索引，也可以修改列
f.reindex(columns = ['pop','year','state','add'])

pop  year state  add
a  1.5  2000  ohio  NaN
b  1.3  2001  ohio  NaN
c  1.7  2002  ohio  NaN
d  2.0  2003   nev  NaN
e  3.5  2004   nev  NaN